# Corrected Feature Extraction Pipeline
- the voltammograms needs to be shfted!
- the peak of pyoc is somewhere at -0.4V
- in the real raw dataset, we need to create a correction, therefore we would consider the mean of the last signals with small dillutions; that value would be the correction constant.

Dataset for lab signals: `Standard calibration in culture media_extended.xlsx`

Dataset for real signals: `Date P.aeruginosa Clinic 788 + ATCC.xlsx`

In [1]:
from voltammogram_signal import Signal
import pandas as pd

In [2]:
df = pd.read_excel("datasets/Date P.aeruginosa Clinic 788 + ATCC.xlsx", sheet_name="788 raw")
df.head()

,6h,Clinic_6 h nediluat_1,Clinic_6 h nediluat_1 - moving average baseline,Clinic_6 h nediluat_2,Clinic_6 h nediluat_2 - moving average baseline,Clinic_6 h nediluat_3,Clinic_6 h nediluat_3 - moving average baseline,Unnamed: 7,9h,Clinic_9 h nediluat_1,...,Clinic_24 h diluat 1/32_2,Clinic_24 h diluat 1/32_2 - moving average baseline,Clinic_24 h diluat 1/32_3,Clinic_24 h diluat 1/32_3 - moving average baseline,Clinic_24 h diluat 1/64_1,Clinic_24 h diluat 1/64_1 - moving average baseline,Clinic_24 h diluat 1/64_2,Clinic_24 h diluat 1/64_2 - moving average baseline,Clinic_24 h diluat 1/64_3,Clinic_24 h diluat 1/64_3 - moving average baseline
0,V,µA,µA,µA,µA,µA,µA,NaN,V,µA,...,µA,µA,µA,µA,µA,µA,µA,µA,µA,µA
1,-0.600097,0.675497,0,0.689496,0,0.626497,0,NaN,-0.600097,0.951995,...,0.916995,0,0.972995,0,0.888996,0,1.203994,0,1.252994,0
2,-0.595262,0.678996,0.045198,0.699996,0.047368,0.626497,0.039375,NaN,-0.595262,0.958995,...,0.895995,0.041562,0.965995,0.056656,0.874996,0.046521,1.168994,0.049656,1.231994,0.061578
3,-0.590427,0.654497,0.037379,0.678996,0.041116,0.608997,0.037625,NaN,-0.590427,0.923995,...,0.867996,0.038588,0.916995,0.033118,0.846996,0.042729,1.112995,0.027519,1.175994,0.038609
4,-0.585592,0.631747,0.031308,0.661497,0.038363,0.579247,0.023624,NaN,-0.585592,0.881996,...,0.832996,0.028612,0.885496,0.027081,0.808496,0.028436,1.074495,0.02288,1.137494,0.033139

In [3]:
df.dropna(axis=1, inplace=True)
df.head()

,6h,Clinic_6 h nediluat_1,Clinic_6 h nediluat_1 - moving average baseline,Clinic_6 h nediluat_2,Clinic_6 h nediluat_2 - moving average baseline,Clinic_6 h nediluat_3,Clinic_6 h nediluat_3 - moving average baseline,9h,Clinic_9 h nediluat_1,Clinic_9 h nediluat_1 - moving average baseline,...,Clinic_24 h diluat 1/32_2,Clinic_24 h diluat 1/32_2 - moving average baseline,Clinic_24 h diluat 1/32_3,Clinic_24 h diluat 1/32_3 - moving average baseline,Clinic_24 h diluat 1/64_1,Clinic_24 h diluat 1/64_1 - moving average baseline,Clinic_24 h diluat 1/64_2,Clinic_24 h diluat 1/64_2 - moving average baseline,Clinic_24 h diluat 1/64_3,Clinic_24 h diluat 1/64_3 - moving average baseline
0,V,µA,µA,µA,µA,µA,µA,V,µA,µA,...,µA,µA,µA,µA,µA,µA,µA,µA,µA,µA
1,-0.600097,0.675497,0,0.689496,0,0.626497,0,-0.600097,0.951995,0,...,0.916995,0,0.972995,0,0.888996,0,1.203994,0,1.252994,0
2,-0.595262,0.678996,0.045198,0.699996,0.047368,0.626497,0.039375,-0.595262,0.958995,0.063875,...,0.895995,0.041562,0.965995,0.056656,0.874996,0.046521,1.168994,0.049656,1.231994,0.061578
3,-0.590427,0.654497,0.037379,0.678996,0.041116,0.608997,0.037625,-0.590427,0.923995,0.051625,...,0.867996,0.038588,0.916995,0.033118,0.846996,0.042729,1.112995,0.027519,1.175994,0.038609
4,-0.585592,0.631747,0.031308,0.661497,0.038363,0.579247,0.023624,-0.585592,0.881996,0.032375,...,0.832996,0.028612,0.885496,0.027081,0.808496,0.028436,1.074495,0.02288,1.137494,0.033139

In [4]:
print(df.columns)

Index(['6h', 'Clinic_6 h nediluat_1',
       'Clinic_6 h nediluat_1 - moving average baseline',
       'Clinic_6 h nediluat_2',
       'Clinic_6 h nediluat_2 - moving average baseline',
       'Clinic_6 h nediluat_3',
       'Clinic_6 h nediluat_3 - moving average baseline', '9h',
       'Clinic_9 h nediluat_1',
       'Clinic_9 h nediluat_1 - moving average baseline',
       ...
       'Clinic_24 h diluat 1/32_2',
       'Clinic_24 h diluat 1/32_2 - moving average baseline',
       'Clinic_24 h diluat 1/32_3',
       'Clinic_24 h diluat 1/32_3 - moving average baseline',
       'Clinic_24 h diluat 1/64_1',
       'Clinic_24 h diluat 1/64_1 - moving average baseline',
       'Clinic_24 h diluat 1/64_2',
       'Clinic_24 h diluat 1/64_2 - moving average baseline',
       'Clinic_24 h diluat 1/64_3',
       'Clinic_24 h diluat 1/64_3 - moving average baseline'],
      dtype='str', length=138)

In [5]:
normalized_currents = df[[col for col in df.columns if 'moving average baseline' in col]]
normalized_currents.head()

,Clinic_6 h nediluat_1 - moving average baseline,Clinic_6 h nediluat_2 - moving average baseline,Clinic_6 h nediluat_3 - moving average baseline,Clinic_9 h nediluat_1 - moving average baseline,Clinic_9 h nediluat_2 - moving average baseline,Clinic_9 h diluat 1/2_1 - moving average baseline,Clinic_9 h diluat 1/2_2 - moving average baseline,Clinic_12 h nediluat_1 - moving average baseline,Clinic_12 h nediluat_2 - moving average baseline,Clinic_12 h diluat 1/2_1 - moving average baseline,...,Clinic_24 h diluat 1/8_3 - moving average baseline,Clinic_24 h diluat 1/16_1 - moving average baseline,Clinic_24 h diluat 1/16_2 - moving average baseline,Clinic_24 h diluat 1/16_3 - moving average baseline,Clinic_24 h diluat 1/32_1 - moving average baseline,Clinic_24 h diluat 1/32_2 - moving average baseline,Clinic_24 h diluat 1/32_3 - moving average baseline,Clinic_24 h diluat 1/64_1 - moving average baseline,Clinic_24 h diluat 1/64_2 - moving average baseline,Clinic_24 h diluat 1/64_3 - moving average baseline
0,µA,µA,µA,µA,µA,µA,µA,µA,µA,µA,...,µA,µA,µA,µA,µA,µA,µA,µA,µA,µA
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0.045198,0.047368,0.039375,0.063875,0.070893,0.046958,0.059718,0.044515,0.051388,0.065606,...,0.054687,0.043968,0.052245,0.048562,0.0525,0.041562,0.056656,0.046521,0.049656,0.061578
3,0.037379,0.041116,0.037625,0.051625,0.06145,0.033541,0.034607,0.034322,0.044643,0.040049,...,0.035962,0.028656,0.047942,0.038588,0.0343,0.038588,0.033118,0.042729,0.027519,0.038609
4,0.031308,0.038363,0.023624,0.032375,0.048507,0.025374,0.030493,0.029378,0.025648,0.042492,...,0.027736,0.023843,0.02614,0.028612,0.026599,0.028612,0.027081,0.028436,0.02288,0.033139

In [6]:
normalized_currents.drop(index=0, inplace=True, axis=0)
normalized_currents.head()

,Clinic_6 h nediluat_1 - moving average baseline,Clinic_6 h nediluat_2 - moving average baseline,Clinic_6 h nediluat_3 - moving average baseline,Clinic_9 h nediluat_1 - moving average baseline,Clinic_9 h nediluat_2 - moving average baseline,Clinic_9 h diluat 1/2_1 - moving average baseline,Clinic_9 h diluat 1/2_2 - moving average baseline,Clinic_12 h nediluat_1 - moving average baseline,Clinic_12 h nediluat_2 - moving average baseline,Clinic_12 h diluat 1/2_1 - moving average baseline,...,Clinic_24 h diluat 1/8_3 - moving average baseline,Clinic_24 h diluat 1/16_1 - moving average baseline,Clinic_24 h diluat 1/16_2 - moving average baseline,Clinic_24 h diluat 1/16_3 - moving average baseline,Clinic_24 h diluat 1/32_1 - moving average baseline,Clinic_24 h diluat 1/32_2 - moving average baseline,Clinic_24 h diluat 1/32_3 - moving average baseline,Clinic_24 h diluat 1/64_1 - moving average baseline,Clinic_24 h diluat 1/64_2 - moving average baseline,Clinic_24 h diluat 1/64_3 - moving average baseline
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0.045198,0.047368,0.039375,0.063875,0.070893,0.046958,0.059718,0.044515,0.051388,0.065606,...,0.054687,0.043968,0.052245,0.048562,0.0525,0.041562,0.056656,0.046521,0.049656,0.061578
3,0.037379,0.041116,0.037625,0.051625,0.06145,0.033541,0.034607,0.034322,0.044643,0.040049,...,0.035962,0.028656,0.047942,0.038588,0.0343,0.038588,0.033118,0.042729,0.027519,0.038609
4,0.031308,0.038363,0.023624,0.032375,0.048507,0.025374,0.030493,0.029378,0.025648,0.042492,...,0.027736,0.023843,0.02614,0.028612,0.026599,0.028612,0.027081,0.028436,0.02288,0.033139
5,0.014737,0.02861,0.011373,0.027124,0.035563,0.024206,0.01938,0.020933,0.018903,0.037933,...,0.01951,0.012029,0.018336,0.025636,0.018898,0.022136,0.021042,0.024643,0.018241,0.02767

In [ ]:
times = [
    6,
    6,
    6,
    9,
    9,
    9,
    9,
    12,
    12,
    12,
    12,
    12,
    12,
    12,
    12,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    20,
    20,
    20,
    20,
    20,
    20,
    20,
    20,
    20,
    20,
    20,
    20,
    20,
    20,
    24,
    24,
    24,
    24,
    24,
    24,
    24,
    24,
    24,
    24,
    24,
    24,
    24,
    24,
    24,
    24,
    24,
    24,
    24,
    24,
    24,
    24
]

df.iloc[1:, 0]

1     -0.600097
2     -0.595262
3     -0.590427
4     -0.585592
5     -0.580757
         ...
225    0.482979
226    0.487814
227    0.492649
228    0.497484
229    0.502319
Name: 6h, Length: 229, dtype: object

In [8]:
Signal.set_common_potential_E(df.iloc[1:, 0])
len(Signal.E)

229

In [ ]:
signals = []

for i, col in enumerate(normalized_currents.columns):
    signal = Signal(normalized_currents[col].values)
    signals.append(signal)
    signal.pplot(start=10, end=200, title=f"Signal ID: {i}, Time: {times[i]}h")